{
    "metadata" : {
        "revision" : 1,
        "name" : "moonlight Markdown"
    },
    "text-styles": {
        "Normal" : {
            "text-color" : "#CCD1D8",
            "selected-text-color" : "#FFFFFF",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Keyword" : {
            "text-color" : "#cfcfc2",
            "selected-text-color" : "#FFFFFF",
            "bold" : true
        },
        "Function" : {
            "text-color" : "#D1B4DE",
            "selected-text-color" : "#FFFFFF"
        },
        "Variable" : {
            "text-color" : "#76CCCC",
            "selected-text-color" : "#FFFFFF"
        },
        "ControlFlow" : {
            "text-color" : "#fdbc4b",
            "selected-text-color" : "#FFFFFF",
            "bold" : true
        },
        "Operator" : {
            "text-color" : "#cfcfc2",
            "selected-text-color" : "#FFFFFF"
        },
        "BuiltIn" : {
            "text-color" : "#B8BFC0",
            "selected-text-color" : "#FFFFFF"
        },
        "Extension" : {
            "text-color" : "#72C7FF",
            "selected-text-color" : "#FFFFFF",
            "bold" : true
        },
        "Preprocessor" : {
            "text-color" : "#7ECFA0",
            "selected-text-color" : "#FFFFFF"
        },
        "Attribute" : {
            "text-color" : "#9BC3DE",
            "selected-text-color" : "#FFFFFF"
        },
        "Char" : {
            "text-color" : "#7AC7F0",
            "selected-text-color" : "#FFFFFF"
        },
        "SpecialChar" : {
            "text-color" : "#7AC7F0",
            "selected-text-color" : "#FFFFFF"
        },
        "String" : {
            "text-color" : "#FAA9A9",
            "selected-text-color" : "#FFFFFF"
        },
        "VerbatimString" : {
            "text-color" : "#EFADB3",
            "selected-text-color" : "#FFFFFF"
        },
        "SpecialString" : {
            "text-color" : "#EFADB3",
            "selected-text-color" : "#FFFFFF"
        },
        "Import" : {
            "text-color" : "#7ECFA0",
            "selected-text-color" : "#FFFFFF"
        },
        "DataType" : {
            "text-color" : "#9BC3DE",
            "selected-text-color" : "#FFFFFF"
        },
        "DecVal" : {
            "text-color" : "#FAAE6A",
            "selected-text-color" : "#FFFFFF"
        },
        "BaseN" : {
            "text-color" : "#FAAE6A",
            "selected-text-color" : "#FFFFFF"
        },
        "Float" : {
            "text-color" : "#FAAE6A",
            "selected-text-color" : "#FFFFFF"
        },
        "Constant" : {
            "text-color" : "#76CCCC",
            "selected-text-color" : "#FFFFFF",
            "bold" : true
        },
        "Comment" : {
            "text-color" : "#BDBEBE",
            "selected-text-color" : "#FFFFFF"
        },
        "Documentation" : {
            "text-color" : "#DDB4B8",
            "selected-text-color" : "#FFFFFF"
        },
        "Annotation" : {
            "text-color" : "#A7C5B2",
            "selected-text-color" : "#FFFFFF"
        },
        "CommentVar" : {
            "text-color" : "#B8BFC0",
            "selected-text-color" : "#FFFFFF"
        },
        "RegionMarker" : {
            "text-color" : "#9BC3DE",
            "selected-text-color" : "#FFFFFF",
            "background-color" : "#153042"
        },
        "Information" : {
            "text-color" : "#E4B58B",
            "selected-text-color" : "#FFFFFF"
        },
        "Warning" : {
            "text-color" : "#EFADB3",
            "selected-text-color" : "#FFFFFF"
        },
        "Alert" : {
            "text-color" : "#95da4c",
            "selected-text-color" : "#FFFFFF",
            "background-color" : "#4d1f24",
            "bold" : true
        },
        "Error" : {
            "text-color" : "#EFADB3",
            "selected-text-color" : "#FFFFFF",
            "underline" : true
        },
        "Others" : {
            "text-color" : "#7ECFA0",
            "selected-text-color" : "#FFFFFF"
        }
   },
    "editor-colors": {
        "background-color" : "#333842",
        "code-folding" : "#9DA6DC",
        "bracket-matching" : "#8e44ad",
        "current-line" : "#444B58",
        "icon-border" : "#3C414D",
        "indentation-line" : "#959DA9",
        "line-numbers" : "#AAB0BE",
        "current-line-number" : "#CCD1D8",
        "mark-bookmark" : "#0404bf",
        "mark-breakpoint-active" : "#8b0607",
        "mark-breakpoint-reached" : "#6d6e07",
        "mark-breakpoint-disabled" : "#820683",
        "mark-execution" : "#4d4e50",
        "mark-warning" : "#f67400",
        "mark-error" : "#da4453",
        "modified-lines" : "#c04900",
        "replace-highlight" : "#808021",
        "saved-lines" : "#1c8042",
        "search-highlight" : "#4DB6AC",
        "selection" : "#0A62CC",
        "separator" : "#7a7c7d",
        "spell-checking" : "#c0392b",
        "tab-marker" : "#A0A8B7",
        "template-background" : "#31363b",
        "template-placeholder" : "#123723",
        "template-focused-placeholder" : "#123723",
        "template-read-only-placeholder" : "#4d1f24",
        "word-wrap-marker" : "#3a3f44"
    }
}
