#include <QTest>
#include <QUrl>
#include <QUrlQuery>

#include <controllers/pdfviewwindowcontroller.h>
#include <core/nodeidentifier.h>
#include <core/servicelocator.h>
#include <core/vxpdfscheme.h>

using namespace vnotex;

namespace tests {

class TestPdfViewWindowController : public QObject {
  Q_OBJECT

private slots:
  // ============ preparePdfUrl ============
  //
  // Since the pdf.js v6 upgrade the viewer page is served over the `vxpdf://`
  // scheme (see src/core/vxpdfscheme.h), so preparePdfUrl no longer sees any
  // filesystem path: it turns a document TOKEN into the viewer URL. The
  // path-shape of the viewer URL is load-bearing — every pdf.js default option
  // resolves relative to it — so it is asserted verbatim.

  void testPreparePdfUrl_validToken() {
    auto state = PdfViewWindowController::preparePdfUrl(QStringLiteral("abc123"));
    QVERIFY(state.valid);
    QVERIFY(!state.templateUrl.isEmpty());

    QCOMPARE(state.templateUrl.scheme(), VxPdfScheme::scheme());
    QCOMPARE(state.templateUrl.host(), VxPdfScheme::host());
    QCOMPARE(state.templateUrl.path(),
             QStringLiteral("/asset/web/pdf.js/web/pdf-viewer-template.html"));

    // No file: URL may survive anywhere in the viewer URL.
    QVERIFY(!state.templateUrl.toString().contains(QStringLiteral("file:")));

    QVERIFY(state.templateUrl.hasQuery());
    const QString query = state.templateUrl.query(QUrl::FullyEncoded);
    QVERIFY(query.startsWith(QStringLiteral("file=")));
    // The `file` value is a COMPLETE percent-encoded document URL, not a bare token.
    QVERIFY(query.contains(QStringLiteral("vxpdf%3A%2F%2Fpdf%2Fdocument%2Fabc123")));
  }

  void testPreparePdfUrl_documentUrlRoundTrips() {
    auto state = PdfViewWindowController::preparePdfUrl(QStringLiteral("tok-42"));
    QVERIFY(state.valid);

    QUrlQuery q(state.templateUrl);
    QCOMPARE(q.queryItemValue(QStringLiteral("file"), QUrl::FullyDecoded),
             VxPdfScheme::documentUrl(QStringLiteral("tok-42")));
  }

  void testPreparePdfUrl_emptyToken() {
    auto state = PdfViewWindowController::preparePdfUrl(QString());
    QVERIFY(!state.valid);
    QVERIFY(state.templateUrl.isEmpty());
  }

  // The token is opaque and generated by the scheme handler, so the special
  // characters that used to come from a file name (# + &) can no longer reach
  // the query. Assert the encoding anyway, so a future non-UUID token scheme
  // cannot silently break the `?file=` parse.
  void testPreparePdfUrl_tokenIsPercentEncoded() {
    auto state = PdfViewWindowController::preparePdfUrl(QStringLiteral("a#b&c+d"));
    QVERIFY(state.valid);
    const QString query = state.templateUrl.query(QUrl::FullyEncoded);
    QVERIFY(!query.contains(QLatin1Char('#')));
    QVERIFY(!query.contains(QLatin1Char('&')));
    QVERIFY(query.contains(QStringLiteral("%23")));
    QVERIFY(query.contains(QStringLiteral("%26")));
    QVERIFY(query.contains(QStringLiteral("%2B")));
  }

  // ============ VxPdfScheme path safety ============

  void testAssetPathSafety_data() {
    QTest::addColumn<QString>("path");
    QTest::addColumn<bool>("safe");

    QTest::newRow("plain") << QStringLiteral("web/pdf.js/build/pdf.mjs") << true;
    QTest::newRow("viewer template") << VxPdfScheme::viewerTemplateRelativePath() << true;
    QTest::newRow("empty") << QString() << false;
    QTest::newRow("absolute") << QStringLiteral("/web/pdf.js/build/pdf.mjs") << false;
    QTest::newRow("outside web") << QStringLiteral("themes/pure/palette.json") << false;
    QTest::newRow("traversal") << QStringLiteral("web/../../secrets.txt") << false;
    QTest::newRow("dot segment") << QStringLiteral("web/./pdf.js/build/pdf.mjs") << false;
    QTest::newRow("backslash") << QStringLiteral("web\\pdf.js\\build\\pdf.mjs") << false;
    QTest::newRow("drive letter") << QStringLiteral("web/C:/boot.ini") << false;
    QTest::newRow("double slash") << QStringLiteral("web//pdf.js/build/pdf.mjs") << false;
  }

  void testAssetPathSafety() {
    QFETCH(QString, path);
    QFETCH(bool, safe);
    QCOMPARE(VxPdfScheme::isSafeAssetPath(path), safe);
  }

  // ============ buildAbsolutePath (external files) ============

  // An external file (e.g. drag&dropped into the main window) is represented by
  // a NodeIdentifier with an EMPTY notebookId and the absolute on-disk path in
  // relativePath. buildAbsolutePath must return that absolute path verbatim
  // (the old code returned empty because NodeIdentifier::isValid() is false when
  // notebookId is empty, which produced a blank PDF page). The external branch
  // touches no service, so an empty ServiceLocator (no vxcore context) suffices.
  void testBuildAbsolutePath_externalFile() {
    ServiceLocator services;
    PdfViewWindowController controller(services);

    NodeIdentifier nodeId;
    nodeId.relativePath = QStringLiteral("C:/tmp/report.pdf");
    QCOMPARE(controller.buildAbsolutePath(nodeId), nodeId.relativePath);
  }

  void testBuildAbsolutePath_externalFileUnicode() {
    ServiceLocator services;
    PdfViewWindowController controller(services);

    NodeIdentifier nodeId;
    // A Chinese-named external PDF ("量子算法综述.pdf").
    nodeId.relativePath = QString::fromUtf8("Q:/tmp/\xE9\x87\x8F\xE5\xAD\x90"
                                            "\xE7\xAE\x97\xE6\xB3\x95\xE7\xBB\xBC\xE8\xBF\xB0.pdf");
    QCOMPARE(controller.buildAbsolutePath(nodeId), nodeId.relativePath);
  }

  void testBuildAbsolutePath_emptyIdentifier() {
    ServiceLocator services;
    PdfViewWindowController controller(services);

    NodeIdentifier nodeId; // empty notebookId + empty relativePath
    QVERIFY(controller.buildAbsolutePath(nodeId).isEmpty());
  }
};

} // namespace tests

QTEST_GUILESS_MAIN(tests::TestPdfViewWindowController)
#include "test_pdfviewwindowcontroller.moc"
