// Tests for ManifestSignature, the minisign verifier that authenticates update
// manifests.
//
// The manifest describes bytes VNote will download and then EXECUTE, so this is
// a code-execution path. TLS plus a SHA-256 taken from the same origin proves
// only that the bytes arrived intact from whoever served them; the signature is
// what proves they came from us.
//
// EVERY vector below was produced by the REFERENCE minisign implementation
// (jedisct1/minisign 0.11), not by this code. Generating fixtures with the
// implementation under test would only prove it agrees with itself.
//
// The keypairs are throwaways created solely for these tests. The production
// key is generated by the release maintainer and its private half never exists
// in this repository.

#include <QtTest>

#include <QByteArray>
#include <QVector>

#include <core/manifestsignature.h>

using namespace vnotex;

namespace tests {

namespace {

// --- Reference vectors (minisign 0.11) ------------------------------------

// Key 1: `minisign -G`. Public key id 202BB16A2F1834A9.
const char *const c_pubKey1 =
    "RWSpNBgvarErINGfzyYvN8eldfAcodQJWLw6/p0fsiTv3QEKLaPI/ALS";

// Key 2: an independent keypair, used for the unknown-key and rotation cases.
const char *const c_pubKey2 =
    "RWTZgeDs0/NDYJvvXtD3DucnNLWWdB9QYlOvTbYWTGNWxW7vaBlHh9i7";

// The exact bytes that were signed. Byte-for-byte fidelity matters: the
// verifier must operate on the manifest AS RECEIVED, never on a re-serialized
// form, or any JSON formatting difference would break verification.
QByteArray message() { return QByteArrayLiteral("{\"schema\":1,\"product\":\"VNote\"}"); }

// `minisign -S -t "vnote test vector"` with key 1.
QByteArray signatureKey1() {
  return QByteArrayLiteral(
      "untrusted comment: signature from minisign secret key\n"
      "RUSpNBgvarErIGBKUWe8KnooR6X5WiixGADt+NfmTSV5Nrdo51u9ErG4PSbQr+f5rsThduwqRgpfnXFarn63OA1sPgd3xNS2Mgg=\n"
      "trusted comment: vnote test vector\n"
      "v3I2Wa6KaksrXfnxVHMXZWgLdqIkD121S0m4JQ/qFoO84nxjFx+ObT2B+XVURBjo+JiOMml28Tdvpz43pOhxAA==\n");
}

// `minisign -S -t "signed by the spare key"` with key 2.
QByteArray signatureKey2() {
  return QByteArrayLiteral(
      "untrusted comment: signature from minisign secret key\n"
      "RUTZgeDs0/NDYGy4sqy92hl+0qRRgRGMeh5V6KCFIZHXFdap8Tfg6GF8MXerJsFGBNBdnBlNGZTor9HHLCV+F33iCBWymYeNDAg=\n"
      "trusted comment: signed by the spare key\n"
      "jNMtkPQvk1ZKsbTVQESQPkL3mYm6QG5ySMGSpa0RonJRq0R2RrZD8NgC/Xgf7kQdN904D3+tEDEkInEcVXweDg==\n");
}

ManifestSignature::PublicKey key(const char *p_encoded) {
  return ManifestSignature::parsePublicKey(QString::fromLatin1(p_encoded));
}

QVector<ManifestSignature::PublicKey> keys(std::initializer_list<const char *> p_encoded) {
  QVector<ManifestSignature::PublicKey> out;
  for (const char *e : p_encoded) {
    out.append(key(e));
  }
  return out;
}

// Replaces line p_index (0-based) of a .minisig.
QByteArray withLine(const QByteArray &p_sig, int p_index, const QByteArray &p_replacement) {
  QList<QByteArray> lines = p_sig.split('\n');
  lines[p_index] = p_replacement;
  return lines.join('\n');
}

} // namespace

class TestManifestSignature : public QObject {
  Q_OBJECT

private slots:
  void cleanup();

  // Public key parsing.
  void testParsePublicKey();
  void testParsePublicKeyRejectsGarbage();

  // The happy path, against the reference implementation's own output.
  void testValidSignature();
  void testTrustedCommentIsReturned();

  // Tampering.
  void testTamperedMessageIsRejected();
  void testTamperedSignatureIsRejected();
  void testTamperedTrustedCommentIsRejected();
  void testUntrustedCommentIsNotAuthenticated();

  // Key selection and rotation.
  void testUnknownKeyIsRejected();
  void testRotationAcceptsEitherConfiguredKey();
  void testWrongKeyCannotVerifyAnothersSignature();

  // Fail-closed and malformed input.
  void testNoTrustedKeysFailsClosed();
  void testLegacyAlgorithmIsRejected();
  void testMalformedSignatures();
  void testMalformedSignatures_data();

  // Production configuration.
  void testProductionKeyListIsCoherent();
};

void TestManifestSignature::cleanup() {
  // Always drop the override so one case cannot leak keys into the next.
  ManifestSignature::testSetTrustedKeys({});
}

// ------------------------------------------------------------ key parsing

void TestManifestSignature::testParsePublicKey() {
  const auto k = key(c_pubKey1);
  QVERIFY(k.isValid());
  QCOMPARE(k.keyId.size(), 8);
  QCOMPARE(k.publicKey.size(), 32);

  // The key id minisign printed for this key is 202BB16A2F1834A9. minisign
  // displays it big-endian while storing it little-endian, so the stored bytes
  // are the reverse.
  QCOMPARE(k.keyId.toHex().toUpper(), QByteArrayLiteral("A934182F6AB12B20"));

  // A whole .pub file (comment line included) parses identically to the body.
  const auto whole = ManifestSignature::parsePublicKey(
      QStringLiteral("untrusted comment: minisign public key 202BB16A2F1834A9\n%1\n")
          .arg(QString::fromLatin1(c_pubKey1)));
  QVERIFY(whole.isValid());
  QCOMPARE(whole.keyId, k.keyId);
  QCOMPARE(whole.publicKey, k.publicKey);
}

void TestManifestSignature::testParsePublicKeyRejectsGarbage() {
  const QStringList bad{
      QString(),
      QStringLiteral("not base64 at all !!!"),
      QStringLiteral("dGlueQ=="),                       // valid base64, wrong length
      QStringLiteral("untrusted comment: only a comment"),
      // Right length, wrong algorithm tag ("XX" instead of "Ed").
      QString::fromLatin1(QByteArray(QByteArrayLiteral("XX") + QByteArray(40, '\0')).toBase64()),
  };
  for (const QString &b : bad) {
    QVERIFY2(!ManifestSignature::parsePublicKey(b).isValid(), qPrintable(b.left(40)));
  }
}

// ------------------------------------------------------------- happy path

void TestManifestSignature::testValidSignature() {
  const auto result =
      ManifestSignature::verify(message(), signatureKey1(), keys({c_pubKey1}));
  QVERIFY2(result == ManifestSignature::Result::Valid,
           qPrintable(ManifestSignature::resultToString(result)));
}

void TestManifestSignature::testTrustedCommentIsReturned() {
  QString comment;
  QCOMPARE(ManifestSignature::verify(message(), signatureKey1(), keys({c_pubKey1}), &comment),
           ManifestSignature::Result::Valid);
  QCOMPARE(comment, QStringLiteral("vnote test vector"));
}

// --------------------------------------------------------------- tampering

void TestManifestSignature::testTamperedMessageIsRejected() {
  // A single flipped byte anywhere in the manifest must invalidate it.
  QByteArray tampered = message();
  tampered.replace("VNote", "VNot3");
  QCOMPARE(ManifestSignature::verify(tampered, signatureKey1(), keys({c_pubKey1})),
           ManifestSignature::Result::BadSignature);

  // Appending is equally fatal, which matters because a manifest is JSON and a
  // trailing object could otherwise smuggle fields past a lax parser.
  QCOMPARE(ManifestSignature::verify(message() + QByteArrayLiteral(" "), signatureKey1(),
                                     keys({c_pubKey1})),
           ManifestSignature::Result::BadSignature);

  QCOMPARE(ManifestSignature::verify(QByteArray(), signatureKey1(), keys({c_pubKey1})),
           ManifestSignature::Result::BadSignature);
}

void TestManifestSignature::testTamperedSignatureIsRejected() {
  // Flip one bit inside the Ed25519 signature, keeping the algorithm tag and
  // key id intact so it still parses and still selects the right key.
  QByteArray sigLine = signatureKey1().split('\n').at(1);
  QByteArray blob = QByteArray::fromBase64(sigLine);
  QVERIFY(blob.size() == 2 + 8 + 64);
  blob[40] = static_cast<char>(blob[40] ^ 0x01);

  const QByteArray tampered = withLine(signatureKey1(), 1, blob.toBase64());
  QCOMPARE(ManifestSignature::verify(message(), tampered, keys({c_pubKey1})),
           ManifestSignature::Result::BadSignature);
}

// The trusted comment is the part minisign presents to a human as
// authenticated. Rewriting it must be caught by the global signature.
void TestManifestSignature::testTamperedTrustedCommentIsRejected() {
  const QByteArray tampered =
      withLine(signatureKey1(), 2, QByteArrayLiteral("trusted comment: VNote 9.9.9 official"));
  QCOMPARE(ManifestSignature::verify(message(), tampered, keys({c_pubKey1})),
           ManifestSignature::Result::BadGlobalSignature);
}

// Conversely, the UNtrusted comment is documented as not covered by any
// signature. Asserting that keeps the distinction honest rather than implied.
void TestManifestSignature::testUntrustedCommentIsNotAuthenticated() {
  const QByteArray altered =
      withLine(signatureKey1(), 0, QByteArrayLiteral("untrusted comment: anything at all"));
  QCOMPARE(ManifestSignature::verify(message(), altered, keys({c_pubKey1})),
           ManifestSignature::Result::Valid);
}

// ------------------------------------------------------- keys and rotation

void TestManifestSignature::testUnknownKeyIsRejected() {
  // Signature made by key 2, but only key 1 is trusted. Reported as UnknownKey
  // rather than BadSignature so a rotated-away key gives an actionable message.
  QCOMPARE(ManifestSignature::verify(message(), signatureKey2(), keys({c_pubKey1})),
           ManifestSignature::Result::UnknownKey);
}

// The whole point of a key LIST: a build must accept signatures from either the
// active key or the cold spare, otherwise rotation is impossible without
// stranding every installed client.
void TestManifestSignature::testRotationAcceptsEitherConfiguredKey() {
  const auto both = keys({c_pubKey1, c_pubKey2});
  QCOMPARE(ManifestSignature::verify(message(), signatureKey1(), both),
           ManifestSignature::Result::Valid);
  QCOMPARE(ManifestSignature::verify(message(), signatureKey2(), both),
           ManifestSignature::Result::Valid);

  // Order must not matter.
  const auto reversed = keys({c_pubKey2, c_pubKey1});
  QCOMPARE(ManifestSignature::verify(message(), signatureKey1(), reversed),
           ManifestSignature::Result::Valid);
}

// Guards against a verifier that ignores the key id and simply tries every key:
// key 2's signature must fail against key 1 even when key 1 is the only one
// offered, and must not be silently accepted by trying harder.
void TestManifestSignature::testWrongKeyCannotVerifyAnothersSignature() {
  // Take key 2's signature but rewrite its key id to key 1's, so key selection
  // succeeds and only the cryptography can reject it.
  const QByteArray k1 = key(c_pubKey1).keyId;
  QByteArray blob = QByteArray::fromBase64(signatureKey2().split('\n').at(1));
  blob.replace(2, 8, k1);

  const QByteArray forged = withLine(signatureKey2(), 1, blob.toBase64());
  QCOMPARE(ManifestSignature::verify(message(), forged, keys({c_pubKey1})),
           ManifestSignature::Result::BadSignature);
}

// ------------------------------------------------------ fail-closed / junk

// "No key configured" must never be read as "signature not required". This is
// the single most important property in the file.
void TestManifestSignature::testNoTrustedKeysFailsClosed() {
  QCOMPARE(ManifestSignature::verify(message(), signatureKey1(),
                                     QVector<ManifestSignature::PublicKey>()),
           ManifestSignature::Result::NoTrustedKeys);
  QVERIFY(ManifestSignature::Result::NoTrustedKeys != ManifestSignature::Result::Valid);
}

void TestManifestSignature::testLegacyAlgorithmIsRejected() {
  // Downgrade the algorithm tag from prehashed `ED` to legacy `Ed`. VNote's
  // signer always emits `ED`, so accepting `Ed` would be an untested branch an
  // attacker could steer into.
  QByteArray blob = QByteArray::fromBase64(signatureKey1().split('\n').at(1));
  blob[1] = 'd';
  const QByteArray downgraded = withLine(signatureKey1(), 1, blob.toBase64());
  QCOMPARE(ManifestSignature::verify(message(), downgraded, keys({c_pubKey1})),
           ManifestSignature::Result::UnsupportedAlgorithm);
}

void TestManifestSignature::testMalformedSignatures_data() {
  QTest::addColumn<QByteArray>("signature");

  QTest::newRow("empty") << QByteArray();
  QTest::newRow("one-line") << QByteArrayLiteral("untrusted comment: x\n");
  QTest::newRow("three-lines")
      << QByteArrayLiteral("untrusted comment: x\nAAAA\ntrusted comment: y\n");
  QTest::newRow("sig-not-base64") << withLine(signatureKey1(), 1, QByteArrayLiteral("!!!not!!!"));
  QTest::newRow("sig-too-short")
      << withLine(signatureKey1(), 1, QByteArray(16, 'A').toBase64());
  QTest::newRow("missing-trusted-comment-prefix")
      << withLine(signatureKey1(), 2, QByteArrayLiteral("comment: no prefix"));
  QTest::newRow("global-not-base64")
      << withLine(signatureKey1(), 3, QByteArrayLiteral("@@@@"));
  QTest::newRow("global-too-short")
      << withLine(signatureKey1(), 3, QByteArray(8, 'A').toBase64());
  QTest::newRow("binary-garbage") << QByteArray(256, '\xff');
}

void TestManifestSignature::testMalformedSignatures() {
  QFETCH(QByteArray, signature);
  // Must be rejected, and must not crash or hang on hostile input.
  const auto result = ManifestSignature::verify(message(), signature, keys({c_pubKey1}));
  QVERIFY2(result != ManifestSignature::Result::Valid,
           qPrintable(ManifestSignature::resultToString(result)));
}

// ------------------------------------------------------------- production

// The compiled-in list is empty in-tree (the maintainer pastes real keys in),
// so this asserts the CONSEQUENCE rather than the contents: with no keys, the
// updater must be inert rather than permissive.
void TestManifestSignature::testProductionKeyListIsCoherent() {
  ManifestSignature::testSetTrustedKeys({});

  for (const auto &k : ManifestSignature::trustedKeys()) {
    QVERIFY2(k.isValid(), "a compiled-in trusted key is malformed");
  }

  if (!ManifestSignature::hasTrustedKeys()) {
    QCOMPARE(ManifestSignature::verify(message(), signatureKey1()),
             ManifestSignature::Result::NoTrustedKeys);
  } else {
    // Once real keys are configured, at least two must be present so the build
    // can rotate without stranding installed clients.
    QVERIFY2(ManifestSignature::trustedKeys().size() >= 2,
             "ship a cold spare key alongside the active one; see the rotation "
             "contract in manifestsignature.cpp");
  }
}

} // namespace tests

QTEST_GUILESS_MAIN(tests::TestManifestSignature)
#include "test_manifestsignature.moc"
