{
    "metadata": {
        "revision": 0,
        "name": "vx-idea",
        "type": "vtextedit"
    },
    "editor-styles": {
        "Text": {
            "//comment": "Support a list of fonts separated by ,",
            "font-family": "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New",
            "font-size": 12,
            "text-color": "#34495e",
            "background-color": "#ffffff",
            "selected-text-color": "@base#content#selection#fg",
            "selected-background-color": "@base#content#selection#bg"
        },
        "CursorLine": {
            "background-color": "#f1f2f6"
        },
        "TrailingSpace": {
            "background-color": "#848487"
        },
        "Tab": {
            "background-color": "#848484"
        },
        "SelectedText": {
            "//comment": "Selected text highlight",
            "text-color": "#34495e",
            "background-color": "#dfdf00"
        },
        "IndicatorsBorder": {
            "text-color": "#686868",
            "background-color": "#e6edf5"
        },
        "CurrentLineNumber": {
            "text-color": "#34495e"
        },
        "Folding": {
            "text-color": "#243656"
        },
        "FoldedFolding": {
            "text-color": "#1F326C"
        },
        "FoldingHighlight": {
            "text-color": "#7284A5"
        },
        "FoldedFoldingRangeLine": {
            "background-color": "#befbdd"
        },
        "IncrementalSearch": {
            "//comment": "Incremental search highlight",
            "text-color": "#2B3C4E",
            "background-color": "#ce93d8"
        },
        "Search": {
            "//comment": "Search highlight",
            "text-color": "#2A3B4C",
            "background-color": "#4db6ac"
        },
        "SearchUnderCursor": {
            "//comment": "Search highlight under cursor",
            "text-color": "#2C3D4F",
            "background-color": "#66bb6a"
        }
    },
    "//comment": "Override the Text style in editor-styles",
    "markdown-editor-styles": {
        "ListItemGuide": {"text-color": "#7B858F"},
        "ActiveListItem": {"background-color": "#f6f8fa"},
        "ConcealedText": {"text-color": "#005BF6", "background-color": "#f6f8fa"},
        "Text": {
            "//comment": "Support a list of fonts separated by ,",
            "font-family": "YaHei Consolas Hybrid, 冬青黑体, Microsoft YaHei, 微软雅黑, Microsoft YaHei UI, WenQuanYi Micro Hei, 文泉驿雅黑, Dengxian, 等线体, STXihei, 华文细黑, Liberation Sans, Droid Sans, NSimSun, 新宋体, SimSun, 宋体, Verdana, Helvetica, sans-serif, Tahoma, Arial, Geneva, Georgia, Times New Roman",
            "font-size": 12,
            "text-color": "#34495e",
            "background-color": "#ffffff",
            "selected-text-color": "@base#content#selection#fg",
            "selected-background-color": "@base#content#selection#bg"
        }
    },
    "markdown-syntax-styles": {
        "H1": {
            "text-color": "#34495e",
            "bold": true,
            "font-size": 17
        },
        "H2": {
            "text-color": "#34495e",
            "bold": true,
            "font-size": 16
        },
        "H3": {
            "text-color": "#34495e",
            "bold": true,
            "font-size": 15
        },
        "H4": {
            "text-color": "#34495e",
            "bold": true,
            "font-size": 14
        },
        "H5": {
            "text-color": "#34495e",
            "bold": true,
            "font-size": 13
        },
        "H6": {
            "text-color": "#34495e",
            "bold": true,
            "font-size": 12
        },
        "HRULE": {
            "text-color": "#34495e",
            "background-color": "#dac7c9"
        },
        "LIST_BULLET": {
            "text-color": "#BC3074",
            "bold": true
        },
        "LIST_ENUMERATOR": {
            "text-color": "#0000ff"
        },
        "LINK": {
            "text-color": "#005BF6"
        },
        "AUTO_LINK_URL": {
            "text-color": "#005BF6"
        },
        "AUTO_LINK_EMAIL": {
            "text-color": "#005BF6"
        },
        "IMAGE": {
            "text-color": "#616161"
        },
        "REFERENCE": {
            "text-color": "#826200"
        },
        "CODE": {
            "text-color": "#8e24aa",
            "font-family": "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "EMPH": {
            "italic": true
        },
        "STRONG": {
            "bold": true
        },
        "HTML_ENTITY": {
            "text-color": "#8900b5"
        },
        "HTML": {
            "text-color": "#8900b5"
        },
        "HTMLBLOCK": {
            "text-color": "#8900b5"
        },
        "COMMENT": {
            "text-color": "#626B6B"
        },
        "VERBATIM": {
            "text-color": "#673ab7",
            "font-family": "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "//comment": "Please modify the syntax highlight theme as well if you change this",
        "FENCEDCODEBLOCK": {
            "text-color": "#673ab7",
            "font-family": "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "BLOCKQUOTE": {
            "text-color": "#007B00"
        },
        "NOTE": {
            "text-color": "#007198"
        },
        "STRIKE": {
            "text-color": "#b71c1c",
            "strike-through": true
        },
        "FRONTMATTER": {
            "text-color": "#6c6c6c"
        },
        "INLINEEQUATION": {
            "text-color": "#00766A",
            "font-family": "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "DISPLAYFORMULA": {
            "text-color": "#00766A",
            "font-family": "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "MARK": {
            "text-color": "#34495e",
            "background-color": "#ffff76"
        },
        "TABLE": {
            "font-family": "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "TABLEBORDER": {
            "text-color": "#BC3074",
            "background-color": "#ffffff"
        }
    }
}