{
    "metadata" : {
        "revision" : 0,
        "name" : "Solarized-dark",
        "type" : "vtextedit"
    },
    "editor-styles" : {
        "Text" : {
            "//comment" : "Support a list of fonts separated by ,",
            "font-family" : "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New",
            "font-size" : 12,
            "text-color" : "#455A64",
            "background-color" : "#FDF6E3",
            "selected-text-color" : "@base#content#selection#fg",
            "selected-background-color" : "@base#content#selection#bg"
        },
        "CursorLine" : {
            "background-color" : "#e4decc"
        },
        "TrailingSpace" : {
            "background-color" : "#737A87"
        },
        "Tab" : {
            "background-color" : "#757A85"
        },
        "SelectedText" : {
            "//comment" : "Selected text highlight",
            "text-color" : "#222222",
            "background-color" : "#dfdf00"
        },
        "IndicatorsBorder" : {
            "text-color" : "#606673",
            "background-color" : "#EEE8D5"
        },
        "CurrentLineNumber" : {
            "text-color" : "#56696F"
        },
        "Folding" : {
            "text-color" : "#6C76AF"
        },
        "FoldedFolding" : {
            "text-color" : "#6F77A5"
        },
        "FoldingHighlight" : {
            "text-color" : "#E4DECC"
        },
        "FoldedFoldingRangeLine" : {
            "background-color" : "#ECE4D3"
        },
        "IncrementalSearch" : {
            "//comment" : "Incremental search highlight",
            "text-color" : "#222222",
            "background-color" : "#ce93d8"
        },
        "Search" : {
            "//comment" : "Search highlight",
            "text-color" : "#222222",
            "background-color" : "#4db6ac"
        },
        "SearchUnderCursor" : {
            "//comment" : "Search highlight under cursor",
            "text-color" : "#222222",
            "background-color" : "#66bb6a"
        }
    },
    "//comment" : "Override the Text style in editor-styles",
    "markdown-editor-styles" : {
        "ListItemGuide" : {"text-color" : "#7C7A6F"},
        "ActiveListItem" : {"background-color" : "#f8f1df"},
        "ConcealedText" : {"text-color" : "#1C6A64", "background-color" : "#f8f1df"},
        "Text" : {
            "//comment" : "Support a list of fonts separated by ,",
            "font-family" : "YaHei Consolas Hybrid, 冬青黑体, Microsoft YaHei, 微软雅黑, Microsoft YaHei UI, WenQuanYi Micro Hei, 文泉驿雅黑, Dengxian, 等线体, STXihei, 华文细黑, Liberation Sans, Droid Sans, NSimSun, 新宋体, SimSun, 宋体, Verdana, Helvetica, Tahoma, Arial, Geneva, Georgia, Times New Roman",
            "font-size" : 12,
            "text-color" : "#455A64",
            "background-color" : "#FDF6E3",
            "selected-text-color" : "@base#content#selection#fg",
            "selected-background-color" : "@base#content#selection#bg"
        },
        "Preview" : {
            "background-color" : "#b0bec5"
        }
    },
    "markdown-syntax-styles" : {
        "H1" : {
            "text-color" : "#815541",
            "bold" : true,
            "font-size" : 17
        },
        "H2" : {
            "text-color" : "#815541",
            "bold" : true,
            "font-size" : 16
        },
        "H3" : {
            "text-color" : "#815541",
            "bold" : true,
            "font-size" : 15
        },
        "H4" : {
            "text-color" : "#815541",
            "bold" : true,
            "font-size" : 14
        },
        "H5" : {
            "text-color" : "#815541",
            "bold" : true,
            "font-size" : 13
        },
        "H6" : {
            "text-color" : "#815541",
            "bold" : true,
            "font-size" : 12
        },
        "HRULE" : {
            "text-color" : "#5C5F66",
            "background-color" : "#E7DADB"
        },
        "LIST_BULLET" : {
            "text-color" : "#815541",
            "bold" : true
        },
        "LIST_ENUMERATOR" : {
            "text-color" : "#815541"
        },
        "LINK" : {
            "text-color" : "#1C6A64"
        },
        "AUTO_LINK_URL" : {
            "text-color" : "#1C6A64"
        },
        "AUTO_LINK_EMAIL" : {
            "text-color" : "#1C6A64"
        },
        "IMAGE" : {
            "text-color" : "#376388"
        },
        "REFERENCE" : {
            "text-color" : "#31676E"
        },
        "CODE" : {
            "text-color" : "#506640",
            "font-family" : "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "EMPH" : {
            "italic" : true
        },
        "STRONG" : {
            "bold" : true
        },
        "HTML_ENTITY" : {
            "text-color" : "#85533B"
        },
        "HTML" : {
            "text-color" : "#85533B"
        },
        "HTMLBLOCK" : {
            "text-color" : "#85533B"
        },
        "COMMENT" : {
            "text-color" : "#59606E"
        },
        "VERBATIM" : {
            "text-color" : "#506640",
            "font-family" : "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "//comment" : "Please modify the syntax highlight theme as well if you change this",
        "FENCEDCODEBLOCK" : {
            "text-color" : "#506640",
            "font-family" : "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "BLOCKQUOTE" : {
            "text-color" : "#525C92"
        },
        "NOTE" : {
            "text-color" : "#6B5494"
        },
        "STRIKE" : {
            "text-color" : "#934A4A",
            "strike-through" : true
        },
        "FRONTMATTER" : {
            "text-color" : "#59606D"
        },
        "INLINEEQUATION" : {
            "text-color" : "#2D6964",
            "font-family" : "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "DISPLAYFORMULA" : {
            "text-color" : "#2D6964",
            "font-family" : "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "MARK" : {
            "text-color" : "#19191A",
            "background-color" : "#898900"
        },
        "TABLE" : {
            "font-family" : "YaHei Consolas Hybrid, Consolas, Monaco, Andale Mono, Monospace, Courier New"
        },
        "TABLEBORDER" : {
            "text-color" : "#815541",
            "background-color" : "#E4DECC"
        }
   }
}
