{
    "metadata": {
        "revision": 1,
        "name": "Dreamy Editor",
        "description": "Apprentice-inspired syntax (https://github.com/romainl/Apprentice)"
    },
    "text-styles": {
        "Normal": {
            "text-color": "#bcbcbc",
            "selected-text-color": "#262626",
            "bold": false,
            "italic": false,
            "underline": false,
            "strike-through": false
        },
        "Keyword": {
            "text-color": "#87afd7",
            "selected-text-color": "#262626"
        },
        "Function": {
            "text-color": "#ffffaf",
            "selected-text-color": "#262626"
        },
        "Variable": {
            "text-color": "#5fafaf",
            "selected-text-color": "#262626"
        },
        "ControlFlow": {
            "text-color": "#87afd7",
            "selected-text-color": "#262626"
        },
        "Operator": {
            "text-color": "#87afd7",
            "selected-text-color": "#262626"
        },
        "BuiltIn": {
            "text-color": "#8787af",
            "selected-text-color": "#262626"
        },
        "Extension": {
            "text-color": "#8787af",
            "selected-text-color": "#262626"
        },
        "Preprocessor": {
            "text-color": "#5fafaf",
            "selected-text-color": "#262626"
        },
        "Attribute": {
            "text-color": "#87afd7",
            "selected-text-color": "#262626"
        },
        "Char": {
            "text-color": "#ff8700",
            "selected-text-color": "#262626"
        },
        "SpecialChar": {
            "text-color": "#87af87",
            "selected-text-color": "#262626"
        },
        "String": {
            "text-color": "#87af87",
            "selected-text-color": "#262626"
        },
        "VerbatimString": {
            "text-color": "#87af87",
            "selected-text-color": "#262626"
        },
        "SpecialString": {
            "text-color": "#87af87",
            "selected-text-color": "#262626"
        },
        "Import": {
            "text-color": "#5fafaf",
            "selected-text-color": "#262626"
        },
        "DataType": {
            "text-color": "#8787af",
            "selected-text-color": "#262626"
        },
        "DecVal": {
            "text-color": "#ff8700",
            "selected-text-color": "#262626"
        },
        "BaseN": {
            "text-color": "#ff8700",
            "selected-text-color": "#262626"
        },
        "Float": {
            "text-color": "#ff8700",
            "selected-text-color": "#262626"
        },
        "Constant": {
            "text-color": "#ff8700",
            "selected-text-color": "#262626"
        },
        "Comment": {
            "text-color": "#9e9e9e",
            "selected-text-color": "#262626"
        },
        "Documentation": {
            "text-color": "#9e9e9e",
            "selected-text-color": "#262626"
        },
        "Annotation": {
            "text-color": "#5fafaf",
            "selected-text-color": "#262626"
        },
        "CommentVar": {
            "text-color": "#9e9e9e",
            "selected-text-color": "#262626"
        },
        "RegionMarker": {
            "text-color": "#5fafaf",
            "selected-text-color": "#262626"
        },
        "Information": {
            "text-color": "#87afd7",
            "selected-text-color": "#262626"
        },
        "Warning": {
            "text-color": "#ffffaf",
            "selected-text-color": "#262626"
        },
        "Alert": {
            "text-color": "#262626",
            "selected-text-color": "#262626",
            "background-color": "#d78787",
            "bold": true
        },
        "Error": {
            "text-color": "#d78787",
            "selected-text-color": "#262626",
            "underline": true
        },
        "Others": {
            "text-color": "#87af87",
            "selected-text-color": "#262626"
        }
    },
    "editor-colors": {
        "background-color": "#262626",
        "code-folding": "#5fafaf",
        "bracket-matching": "#585858",
        "current-line": "#303030",
        "icon-border": "#1c1c1c",
        "indentation-line": "#444444",
        "line-numbers": "#9e9e9e",
        "current-line-number": "#bcbcbc",
        "mark-bookmark": "#87afd7",
        "mark-breakpoint-active": "#d78787",
        "mark-breakpoint-reached": "#ff8700",
        "mark-breakpoint-disabled": "#585858",
        "mark-execution": "#5fafaf",
        "mark-warning": "#ffffaf",
        "mark-error": "#d78787",
        "modified-lines": "#ff8700",
        "replace-highlight": "#d78787",
        "saved-lines": "#87af87",
        "search-highlight": "#ffffaf",
        "selection": "#87afd7",
        "separator": "#444444",
        "spell-checking": "#d78787",
        "tab-marker": "#585858",
        "template-background": "#303030",
        "template-placeholder": "#444444",
        "template-focused-placeholder": "#585858",
        "template-read-only-placeholder": "#303030",
        "word-wrap-marker": "#444444"
    }
}
