{
    "metadata" : {
        "revision" : 1,
        "name" : "vue-dark Editor"
    },
    "text-styles": {
        "Normal" : {
            "text-color" : "#CCD1D8",
            "selected-text-color" : "#FFFFFF",
            "bold" : false,
            "italic" : false,
            "underline" : false,
            "strike-through" : false
        },
        "Keyword" : {
            "text-color" : "#cfcfc2",
            "selected-text-color" : "#FFFFFF",
            "bold" : true
        },
        "Function" : {
            "text-color" : "#C9A5D7",
            "selected-text-color" : "#FFFFFF"
        },
        "Variable" : {
            "text-color" : "#59C1C1",
            "selected-text-color" : "#FFFFFF"
        },
        "ControlFlow" : {
            "text-color" : "#fdbc4b",
            "selected-text-color" : "#FFFFFF",
            "bold" : true
        },
        "Operator" : {
            "text-color" : "#cfcfc2",
            "selected-text-color" : "#FFFFFF"
        },
        "BuiltIn" : {
            "text-color" : "#ABB3B4",
            "selected-text-color" : "#FFFFFF"
        },
        "Extension" : {
            "text-color" : "#52BAFF",
            "selected-text-color" : "#FFFFFF",
            "bold" : true
        },
        "Preprocessor" : {
            "text-color" : "#63C58C",
            "selected-text-color" : "#FFFFFF"
        },
        "Attribute" : {
            "text-color" : "#87B8D8",
            "selected-text-color" : "#FFFFFF"
        },
        "Char" : {
            "text-color" : "#5DBCED",
            "selected-text-color" : "#FFFFFF"
        },
        "SpecialChar" : {
            "text-color" : "#5DBCED",
            "selected-text-color" : "#FFFFFF"
        },
        "String" : {
            "text-color" : "#F89797",
            "selected-text-color" : "#FFFFFF"
        },
        "VerbatimString" : {
            "text-color" : "#EB9CA4",
            "selected-text-color" : "#FFFFFF"
        },
        "SpecialString" : {
            "text-color" : "#EB9CA4",
            "selected-text-color" : "#FFFFFF"
        },
        "Import" : {
            "text-color" : "#63C58C",
            "selected-text-color" : "#FFFFFF"
        },
        "DataType" : {
            "text-color" : "#87B8D8",
            "selected-text-color" : "#FFFFFF"
        },
        "DecVal" : {
            "text-color" : "#F99C49",
            "selected-text-color" : "#FFFFFF"
        },
        "BaseN" : {
            "text-color" : "#F99C49",
            "selected-text-color" : "#FFFFFF"
        },
        "Float" : {
            "text-color" : "#F99C49",
            "selected-text-color" : "#FFFFFF"
        },
        "Constant" : {
            "text-color" : "#59C1C1",
            "selected-text-color" : "#FFFFFF",
            "bold" : true
        },
        "Comment" : {
            "text-color" : "#B0B2B2",
            "selected-text-color" : "#FFFFFF"
        },
        "Documentation" : {
            "text-color" : "#D7A5AA",
            "selected-text-color" : "#FFFFFF"
        },
        "Annotation" : {
            "text-color" : "#96BAA4",
            "selected-text-color" : "#FFFFFF"
        },
        "CommentVar" : {
            "text-color" : "#ABB3B4",
            "selected-text-color" : "#FFFFFF"
        },
        "RegionMarker" : {
            "text-color" : "#87B8D8",
            "selected-text-color" : "#FFFFFF",
            "background-color" : "#153042"
        },
        "Information" : {
            "text-color" : "#DFA674",
            "selected-text-color" : "#FFFFFF"
        },
        "Warning" : {
            "text-color" : "#EB9CA4",
            "selected-text-color" : "#FFFFFF"
        },
        "Alert" : {
            "text-color" : "#95da4c",
            "selected-text-color" : "#FFFFFF",
            "background-color" : "#4d1f24",
            "bold" : true
        },
        "Error" : {
            "text-color" : "#EB9CA4",
            "selected-text-color" : "#FFFFFF",
            "underline" : true
        },
        "Others" : {
            "text-color" : "#63C58C",
            "selected-text-color" : "#FFFFFF"
        }
   },
    "editor-colors": {
        "background-color" : "#242424",
        "code-folding" : "#9DA6DC",
        "bracket-matching" : "#8e44ad",
        "current-line" : "#424242",
        "icon-border" : "#2F2F2F",
        "indentation-line" : "#3a3f44",
        "line-numbers" : "#9A9A9A",
        "current-line-number" : "#CCD1D8",
        "mark-bookmark" : "#0404bf",
        "mark-breakpoint-active" : "#8b0607",
        "mark-breakpoint-reached" : "#6d6e07",
        "mark-breakpoint-disabled" : "#820683",
        "mark-execution" : "#4d4e50",
        "mark-warning" : "#f67400",
        "mark-error" : "#da4453",
        "modified-lines" : "#c04900",
        "replace-highlight" : "#808021",
        "saved-lines" : "#1c8042",
        "search-highlight" : "#4DB6AC",
        "selection" : "#0A62CC",
        "separator" : "#7a7c7d",
        "spell-checking" : "#c0392b",
        "tab-marker" : "#A0A8B7",
        "template-background" : "#31363b",
        "template-placeholder" : "#123723",
        "template-focused-placeholder" : "#123723",
        "template-read-only-placeholder" : "#4d1f24",
        "word-wrap-marker" : "#3a3f44"
    }
}
